### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by creWn** [DocsVision/WebClient-JsDocApi#2]
Hi, I can't use this API documentation because it throws 404 error if I click on any link.
https://docsvision.github.io/WebClient-JsDocApi/globals.html

**Comment by oleg-borisov** [comment]
Hello, the WebClient-JsDocApi has moved to a new address. Use [that](https://docsvision.com/docs/webclient/5.5.14/JsDocApi/index.html) link instead of yours.

**Comment by elkhovd** [comment]
fixed
